/**
 * Blob URLs for local videos. Generated by: npm run upload-local-videos-to-blob
 */

export const LOCAL_VIDEO_BLOB_URLS: Record<string, string> = {
  "22": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-22.mp4",
  "54": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-54.mp4",
  "74": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-74.mp4",
  "103": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-103.mp4",
  "195": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-195.mp4",
  "215": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-215.mp4",
  "232": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-232.mp4",
  "635": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-635.mp4",
  "1043": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-1043.mp4",
  "1559": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-1559.mp4",
  "1579": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-1579.mp4",
  "221616939_240p_h264_1046_cpspoTaKuCLnnIqh_1773519504": "https://ync67dqmie5h8nkz.public.blob.vercel-storage.com/videos/local-221616939_240p_h264_1046_cpspoTaKuCLnnIqh_1773519504.mp4",
};
