/**
 * SEO keywords for crawlers — used in meta keywords and JSON-LD only.
 * Not displayed on page. Captures high-volume and common typo searches.
 */
export const SEO_KEYWORDS = [
  // Primary (high volume)
  "bangla choti",
  "bangla choti golpo",
  "bangla choti kahini",
  "bangla choti golpo in bengali",
  "bangla sex",
  "bangla sex video",
  "bangla sex clips",
  // Common typos / variants (user search behavior)
  "bangla choti gplpo",
  "bangla bangla choti golpo",
  "bangla chotie golpo",
  "bangla choty galpo",
  "bangla choty kahini",
  "choty bangla golpo",
  "bangla sex bideo com",
  "bangla sex viedo com",
  "bangla sexe",
  "www bangla sex vedo com",
  "sexe bangla",
  "sex sex bangla sex",
  "sex sex bangla",
  // Core terms
  "বাংলা চটি",
  "choti kahini",
  "choti golpo",
  "bangla sex story",
  "bangla porn video",
  "sex video",
  "choti video",
  "bongochoti",
  "panu golpo",
  // Long-tail / topical
  "bangla choti online",
  "free bangla choti",
  "bangla choti story",
  "বাংলা চটি গল্প",
  "bangla choti golpo bangla",
  "bangla choti new",
  "panu",
  "panu video",
  "choti book",
  "choti library",
  "bangla sex story bangla",
  "bangla sex story book",
  "real bangla choti",
  "bangla choti official",
  "bongochoti com",
  "desi bangla video",
  "bangla bhabhi sex",
  "new bangla choti golpo",
  "bangla sex kahini",
  "bangla erotic story",
  "bangla hot video",
  "bangla amateur sex",
  "bangla choti app",
  "bangla sex story online",
  "গরম চটি গল্প",
  "বাংলা সেক্স ভিডিও",
  "বৌদির চটি",
  "মামী চটি",
  "ভাবী চটি",
  "পরকীয়া চটি গল্প",
];
