/**
 * Upload videos from public/Videos to Vercel Blob and update lib/localVideoBlobUrls.ts.
 * Run: npx tsx scripts/upload-local-videos-to-blob.ts
 *
 * Prerequisites: BLOB_READ_WRITE_TOKEN in .env.local
 */

import "dotenv/config";
import { config } from "dotenv";
config({ path: ".env.local" });
import * as fs from "fs";
import * as path from "path";
import { put } from "@vercel/blob";

function getBlobToken(): string | null {
  return (
    process.env.BLOB_READ_WRITE_TOKEN?.trim() ||
    process.env.VERCEL_BLOB_READ_WRITE_TOKEN?.trim() ||
    process.env.BONGOCHOTI_BLOB_READ_WRITE_TOKEN?.trim() ||
    null
  );
}

async function main() {
  const token = getBlobToken();
  if (!token) {
    console.error("BLOB_READ_WRITE_TOKEN not set. Add to .env.local and run again.");
    process.exit(1);
  }

  const videosDir = path.join(process.cwd(), "public", "Videos");
  if (!fs.existsSync(videosDir)) {
    console.error("public/Videos folder not found.");
    process.exit(1);
  }

  const files = fs.readdirSync(videosDir).filter((f) => /\.mp4$/i.test(f)).sort();
  if (files.length === 0) {
    console.error("No .mp4 files in public/Videos");
    process.exit(1);
  }

  console.log(`Uploading ${files.length} videos to Vercel Blob...\n`);

  const blobUrls: Record<string, string> = {};

  for (let i = 0; i < files.length; i++) {
    const filename = files[i];
    const baseId = filename.replace(/\.mp4$/i, "");
    const filePath = path.join(videosDir, filename);
    const buffer = fs.readFileSync(filePath);

    process.stdout.write(`[${i + 1}/${files.length}] ${filename} (${(buffer.length / 1024 / 1024).toFixed(1)} MB) `);

    try {
      const { url } = await put(`videos/local-${baseId}.mp4`, buffer, {
        access: "public",
        contentType: "video/mp4",
        addRandomSuffix: false,
        allowOverwrite: true,
        token,
      });
      blobUrls[baseId] = url;
      console.log("✓");
    } catch (err) {
      console.log("✗", err instanceof Error ? err.message : String(err));
    }

    await new Promise((r) => setTimeout(r, 500));
  }

  // Write lib/localVideoBlobUrls.ts
  const outPath = path.join(process.cwd(), "lib", "localVideoBlobUrls.ts");
  const lines = [
    "/**",
    " * Blob URLs for local videos. Generated by: npm run upload-local-videos-to-blob",
    " */",
    "",
    "export const LOCAL_VIDEO_BLOB_URLS: Record<string, string> = {",
    ...Object.entries(blobUrls).map(([k, v]) => `  "${k}": "${v}",`),
    "};",
    "",
  ];
  fs.writeFileSync(outPath, lines.join("\n"), "utf-8");

  console.log(`\n✓ Updated ${outPath} with ${Object.keys(blobUrls).length} Blob URLs`);
  console.log("  Run: npm run build && npm run deploy");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
